# Dean DigitalOcean Configuration
# Optimized for continuous operation with advanced rate limiting

# ML System Configuration
ml_system:
  enabled: true
  learning_rate: 0.01
  confidence_threshold: 0.7
  retrain_frequency_hours: 6  # Retrain every 6 hours for continuous learning
  batch_size: 100  # Process data in smaller batches
  max_features: 50  # Limit features to prevent overfitting

# Rate Limiting Configuration - 24/7 UI PROTECTION
rate_limiting:
  # Meta API Settings - MAXIMUM UI PROTECTION
  request_delay: 2.0  # Very slow requests to ensure UI availability
  peak_hours_delay: 3.0  # Even slower during peak hours (9 AM - 6 PM)
  night_hours_delay: 1.5  # Slightly faster during night hours
  max_concurrent_insights: 1  # SINGLE concurrent request for UI protection
  retry_max: 12  # More retries for reliability
  backoff_base: 2.0  # Stronger exponential backoff
  jitter: 0.5  # More jitter to prevent burst alignment
  
  # Usage Monitoring - AGGRESSIVE THROTTLING
  usage_threshold: 0.6  # Pause when usage > 60% (very conservative)
  throttle_check_interval: 60  # Check usage every minute
  emergency_threshold: 0.8  # Emergency stop at 80%
  
  # Special handling for UI-critical errors - MAXIMUM PROTECTION
  insights_platform_wait: 300  # Wait 5 minutes for 1504022 errors
  app_level_wait: 180  # Wait 3 minutes for 1504039 errors
  ui_protection_mode: true  # Enable maximum UI protection

# Continuous Operation Settings - 24/7 OPTIMIZED
continuous:
  enabled: true
  run_interval: 300  # 5 minutes between runs (24/7)
  peak_hours_interval: 180  # 3 minutes during peak hours (9 AM - 6 PM Amsterdam)
  off_peak_interval: 300    # 5 minutes during off-peak hours
  night_interval: 600       # 10 minutes during night hours (12 AM - 6 AM)
  
  # 24/7 Intelligent scheduling
  amsterdam_timezone: true
  peak_hours_start: 9   # 9 AM Amsterdam time
  peak_hours_end: 18    # 6 PM Amsterdam time
  night_hours_start: 0  # 12 AM Amsterdam time
  night_hours_end: 6    # 6 AM Amsterdam time
  
  # Data collection optimization
  max_data_points_per_run: 50  # Limit data collection per run
  prioritize_recent_data: true  # Focus on recent performance
  skip_heavy_breakdowns: true   # Skip heavy breakdowns during continuous mode

# ML Data Feeding Strategy - 24/7 CONTINUOUS LEARNING
ml_data_feeding:
  # 24/7 Continuous learning approach
  feed_frequency: 180  # Feed data every 3 minutes (24/7)
  peak_hours_frequency: 120  # Every 2 minutes during peak hours
  night_hours_frequency: 300  # Every 5 minutes during night hours
  batch_processing: true  # Process data in batches
  incremental_learning: true  # Learn incrementally from new data
  
  # Data prioritization - MAXIMUM EFFICIENCY
  prioritize_high_performance: true  # Focus on high-performing ads
  prioritize_recent_data: true  # Focus on recent data
  balance_data_types: true  # Balance between different ad types
  prioritize_active_ads: true  # Focus on currently active ads
  
  # Learning optimization - 24/7 ADAPTIVE
  adaptive_learning_rate: true  # Adjust learning rate based on performance
  feature_importance_tracking: true  # Track which features matter most
  model_ensemble: true  # Use multiple models for better predictions
  real_time_learning: true  # Learn from every data point
  continuous_retraining: true  # Retrain models continuously

# Monitoring and Health Checks
monitoring:
  health_check_interval: 300  # Check system health every 5 minutes
  log_level: "INFO"
  performance_tracking: true
  error_alerting: true
  
  # ML System Monitoring
  ml_accuracy_tracking: true
  ml_prediction_monitoring: true
  ml_model_performance_tracking: true
  
  # Rate Limit Monitoring
  api_usage_tracking: true
  rate_limit_alerting: true
  ui_interference_detection: true

# DigitalOcean Specific Settings
digitalocean:
  # Resource limits
  memory_limit: "512M"
  cpu_quota: "50%"
  
  # Logging
  log_rotation: true
  log_retention_days: 7
  
  # Service management
  auto_restart: true
  restart_delay: 30  # seconds
  max_restarts: 5  # per hour
