# Smart Slack Notification Configuration
# Reduces spam while maintaining rich content

# Notification Frequency Control
notifications:
  # Main summary reports (reduced frequency)
  daily_summary:
    enabled: true
    frequency: "once_per_day"  # Only once per day
    time: "09:00"  # 9 AM Amsterdam time
    content: "full_summary"  # Rich content with all metrics
  
  # ML learning updates (reduced frequency)
  ml_learning:
    enabled: true
    frequency: "every_6_hours"  # Every 6 hours instead of every run
    content: "learning_progress"  # Focus on learning progress
  
  # Performance alerts (keep important ones)
  performance_alerts:
    enabled: true
    frequency: "immediate"  # Keep important alerts
    content: "critical_only"  # Only critical issues
  
  # Data collection (reduced frequency)
  data_collection:
    enabled: true
    frequency: "every_2_hours"  # Every 2 hours instead of every run
    content: "summary_only"  # Just summary, not detailed logs

# Content Filtering
content_filters:
  # Skip these types of messages
  skip_messages:
    - "data_stored"  # Skip "Data stored in Supabase" messages
    - "ml_analysis_completed"  # Skip "ML analysis completed" messages
    - "performance_data_inserted"  # Skip detailed insertion logs
    - "lifecycle_data_inserted"  # Skip lifecycle insertion logs
  
  # Keep these important messages
  keep_messages:
    - "ml_health_report"  # Keep ML health reports
    - "performance_summary"  # Keep performance summaries
    - "critical_alerts"  # Keep critical alerts
    - "learning_events"  # Keep learning events

# Smart Aggregation
aggregation:
  # Group similar messages
  group_similar: true
  max_messages_per_hour: 3  # Max 3 messages per hour
  batch_window: "5_minutes"  # Batch messages within 5 minutes
  
  # Priority levels
  priorities:
    critical: 1  # Always send
    important: 2  # Send if not too frequent
    info: 3  # Send only if aggregated
    debug: 4  # Skip most debug messages

# Time-based Controls
time_controls:
  # Quiet hours (reduce notifications)
  quiet_hours:
    enabled: true
    start: "22:00"  # 10 PM
    end: "08:00"    # 8 AM
    timezone: "Europe/Amsterdam"
    reduce_by: 0.8  # 80% reduction during quiet hours
  
  # Peak hours (normal notifications)
  peak_hours:
    start: "09:00"  # 9 AM
    end: "18:00"    # 6 PM
    timezone: "Europe/Amsterdam"
    frequency: "normal"

# Message Templates
templates:
  # Daily summary template
  daily_summary: |
    🤖 **Dean Daily Report** - {date}
    
    📊 **Performance Summary:**
    • Total Ads: {total_ads}
    • Total Spend: €{total_spend}
    • Total Purchases: {total_purchases}
    • Avg CPA: €{avg_cpa}
    • Avg ROAS: {avg_roas}
    
    🧠 **ML Intelligence:**
    • Status: {ml_status}
    • Models Active: {active_models}
    • Predictions Made: {predictions_24h}
    • Learning Events: {learning_events_24h}
    
    🎯 **Key Insights:**
    {key_insights}
    
    ⚡ **System Health:**
    • Uptime: {uptime}
    • Error Rate: {error_rate}%
    • Data Points: {data_points_24h}
  
  # ML learning template
  ml_learning: |
    🧠 **ML Learning Update** - {time}
    
    📈 **Learning Progress:**
    • Status: {ml_status}
    • Models Trained: {models_trained}
    • Recent Training: {recent_training}
    • Data Points: {data_points_24h}
    
    🎯 **Performance:**
    • Predictions: {predictions_24h}
    • Accuracy: {avg_accuracy}%
    • Confidence: {avg_confidence}%
  
  # Critical alert template
  critical_alert: |
    🚨 **Critical Alert** - {time}
    
    {alert_message}
    
    🔧 **Action Required:**
    {action_required}
