name: creative-runner

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes UTC
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: creative-runner
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      FB_APP_ID: ${{ secrets.FB_APP_ID }}
      FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
      FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
      FB_AD_ACCOUNT_ID: ${{ secrets.FB_AD_ACCOUNT_ID }}
      FB_PIXEL_ID: ${{ secrets.FB_PIXEL_ID }}
      FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      STORE_URL: ${{ secrets.STORE_URL }}
      TIMEZONE: ${{ secrets.TIMEZONE }}
      FB_API_VERSION: ${{ secrets.FB_API_VERSION }}
      MODE: ${{ secrets.MODE }}
      DRY_RUN: ${{ secrets.DRY_RUN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_ALERTS: ${{ secrets.SLACK_WEBHOOK_ALERTS }}
      SLACK_WEBHOOK_DIGEST: ${{ secrets.SLACK_WEBHOOK_DIGEST }}
      SLACK_WEBHOOK_SCALE: ${{ secrets.SLACK_WEBHOOK_SCALE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data dirs exist
        run: |
          mkdir -p dean/data
          mkdir -p dean/data/digests

      - name: Run workflow (all stages)
        run: |
          python dean/src/main.py --stage all --settings dean/config/settings.yaml --rules dean/config/rules.yaml
